name: DockerBuildPushKeycloak

on:
  push:
    branches: [ keycloak-features ]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:keycloak -f docker/Dockerfile.keycloak .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:keycloak
